spring:

  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/crud
    username: rey
    password: perrito

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  pattern:
    dateformat: hh:mm
    console: "%-5level : %msg%n"
    #console: "%d %-5level %logger : %msg%n"
  #level:
    #org.springframework: info
    #org.hibernate: debug

server:
  port: 8080
